[package]
name = "rust"
version = "0.1.0"
authors = ["Colin Walters <walters@verbum.org>"]

[dependencies]
clap = "2"
git2 = "0.6.11"
hex = "0.3"
openssl = "0.10"

[[bin]]
name = "git-rustevtag"
test = false
doc = false
