name: CI checks

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  check:
    name: Build with Autotools and gcc, and test
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Install build-dependencies
      run: sudo ./packaging/builddeps.sh
    - name: Create logs dir
      run: mkdir test-logs
    - name: autogen.sh
      run: NOCONFIGURE=1 ./autogen.sh
    - name: configure
      run: |
        mkdir _build
        pushd _build
        ../configure \
          --enable-installed-tests \
          --enable-man \
          ${NULL+}
        popd
      env:
        CFLAGS: >-
          -O2
          -Wp,-D_FORTIFY_SOURCE=2
          -fsanitize=address
          -fsanitize=undefined
    - name: make
      run: |
        make -C _build -j $(getconf _NPROCESSORS_ONLN) V=1
    - name: check
      run: |
        make -C _build -j $(getconf _NPROCESSORS_ONLN) check VERBOSE=1
      env:
        ASAN_OPTIONS: detect_leaks=0
    - name: install
      run: |
        make -C _build install DESTDIR="$(pwd)/DESTDIR"
        ( cd DESTDIR && find -ls )
        sudo make -C _build install
    - name: installed-tests
      run: |
        ginsttest-runner -L test-logs --tap git-evtag
      env:
        ASAN_OPTIONS: detect_leaks=0
    - name: distcheck
      run: |
        make -C _build -j $(getconf _NPROCESSORS_ONLN) distcheck VERBOSE=1
      env:
        ASAN_OPTIONS: detect_leaks=0
    - name: Collect test logs on failure
      if: failure() || cancelled()
      run: |
        mv _build/test-suite/*.log test-logs/ || true
        mv _build/tests/*.log test-logs/ || true
    - name: Upload test logs
      uses: actions/upload-artifact@v1
      if: failure() || cancelled()
      with:
        name: test logs
        path: test-logs

  meson:
    name: Build with Meson and gcc, and test
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: Install build-dependencies
      run: sudo ./packaging/builddeps.sh
    - name: Create logs dir
      run: mkdir test-logs
    - name: configure
      run: |
        meson setup -Dinstall_tests=true -Dman=enabled _build
    - name: compile
      run: |
        meson compile -C _build -v
    - name: test
      run: |
        meson test -C _build -v
    - name: install
      run: |
        DESTDIR="$(pwd)/DESTDIR" meson install -C _build
        ( cd DESTDIR && find -ls )
        sudo meson install -C _build
    - name: installed-tests
      run: |
        ginsttest-runner -L test-logs --tap git-evtag
    - name: Collect test logs on failure
      if: failure() || cancelled()
      run: |
        mv _build/meson-logs/* test-logs/ || true
    - name: Upload test logs
      uses: actions/upload-artifact@v1
      if: failure() || cancelled()
      with:
        name: Meson logs
        path: test-logs

  clang:
    name: Build with clang
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Install build-dependencies
      run: sudo ./packaging/builddeps.sh --clang
    - name: autogen.sh
      run: NOCONFIGURE=1 ./autogen.sh
    # Do this one as an in-tree build to prove we can
    - name: configure
      run: |
        ./configure \
          --enable-installed-tests \
          --enable-man \
          ${NULL+}
      env:
        CC: clang
        CFLAGS: >-
          -O2
          -Werror=unused-variable
    - name: make
      run: make -j $(getconf _NPROCESSORS_ONLN) V=1
