name: CI checks

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  check:
    name: Build with Meson and gcc, and test
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Install build-dependencies
      run: sudo ./packaging/builddeps.sh
    - name: Create logs dir
      run: mkdir test-logs
    - name: configure
      run: |
        meson setup \
          -Db_sanitize=address,undefined \
          -Dinstall_tests=true \
          -Dman=enabled \
          _build
      env:
        CFLAGS: >-
          -O2
          -Wp,-D_FORTIFY_SOURCE=2
    - name: compile
      run: |
        meson compile -C _build -v
    - name: test
      run: |
        meson test -C _build -v
      env:
        ASAN_OPTIONS: detect_leaks=0
    - name: install
      run: |
        DESTDIR="$(pwd)/DESTDIR" meson install -C _build
        ( cd DESTDIR && find -ls )
        sudo meson install -C _build
    - name: installed-tests
      run: |
        ginsttest-runner -L test-logs --tap git-evtag
      env:
        ASAN_OPTIONS: detect_leaks=0
    - name: dist
      run: |
        meson dist -C _build
      env:
        ASAN_OPTIONS: detect_leaks=0
    - name: Collect test logs on failure
      if: failure() || cancelled()
      run: |
        mv _build/meson-logs/* test-logs/ || true
    - name: Upload test logs
      uses: actions/upload-artifact@v1
      if: failure() || cancelled()
      with:
        name: Meson logs
        path: test-logs

  clang:
    name: Build with clang
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Install build-dependencies
      run: sudo ./packaging/builddeps.sh --clang
    - name: configure
      run: |
        meson setup \
          -Dinstall_tests=true \
          -Dman=enabled \
          _build
      env:
        CC: clang
        CFLAGS: >-
          -O2
          -Werror=unused-variable
    - name: compile
      run: |
        meson compile -C _build -v
